### ISSUE TITLE
City Data Exploration

### ISSUE THREAD

**Issue by craigbunyan** [CRALJA/laughing-dollop#7]
See what data is available for cities from brainstorm: 
(from 2010/2011 onward) 
- Population (split by age)
- Deprivation
- Crime
- Public Transport (usage, availability, area covered)
- Taxi
- Phone Signal
- Housing Prices

**Comment by jacobpryce** [comment]
Phone signal update: 
Data unavailable at the city level granularity that we require it to be. Only available for the country as a whole. However, a heat map is available.
